import type { Metadata } from "next";
import { Outfit } from "next/font/google"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "./ConvexClientProvider";



export const metadata: Metadata = {
  title: "AI Trip Planner",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
     appearance={{
        variables: {
          colorPrimary: "#FF4404", // sua cor primária
          colorTextOnPrimaryBackground: "#ffffff", // texto no botão
        },
        elements: {
          buttonPrimary: "bg-[#E02020] hover:bg-[#c91c1c] text-white",
        },
      }} 
      >
      <html lang="en">
        <body
          className={outfit.className}
        >
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
